name: reviewdog
on: [pull_request]

jobs:
  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        uses: ./
        with:
          tool_name: actionlint
          fail_level: error
      - run: |
          echo "${{ format('{0}{1}', 1, 2, 3) }}"
          cd dir; process *; cd ..;         # Use subshells instead

  reviewdog:
    name: runner / reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint w/ reviewdog
        uses: ./
        with:
          actionlint_flags: examples/broken-workflow.yml
          tool_name: reviewdog

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint w/ shellcheck
        uses: ./
        with:
          actionlint_flags: examples/shellcheck.yml
          tool_name: shellcheck

  pyflakes:
    name: runner / pyflakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint w/ pyflakes
        uses: ./
        with:
          actionlint_flags: examples/pyflakes.yml
          tool_name: pyflakes
