name: reviewdog
on: [pull_request]

jobs:
  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        uses: ./
        with:
          tool_name: actionlint
          fail_level: info
      - run: |
          var = 42                          # Spaces around = in assignments
          $foo=42                           # $ in assignments
          for $var in *; do ...             # $ in for loop variables
          var$n="Hello"                     # Wrong indirect assignment
          echo ${var$n}                     # Wrong indirect reference
          var=(1, 2, 3)                     # Comma separated arrays
          array=( [index] = value )         # Incorrect index initialization
          echo $var[14]                     # Missing {} in array references
          echo "Argument 10 is $10"         # Positional parameter misreference
          if $(myfunction); then ..; fi     # Wrapping commands in $()
          else if othercondition; then ..   # Using 'else if'
          f; f() { echo "hello world; }     # Using function before definition
          [ false ]                         # 'false' being true
          if ( -f file )                    # Using (..) instead of test

  reviewdog:
    name: runner / reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint w/ reviewdog
        uses: ./
        with:
          actionlint_flags: examples/broken-workflow.yml
          tool_name: reviewdog

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint w/ shellcheck
        uses: ./
        with:
          actionlint_flags: examples/shellcheck.yml
          tool_name: shellcheck

  pyflakes:
    name: runner / pyflakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint w/ pyflakes
        uses: ./
        with:
          actionlint_flags: examples/pyflakes.yml
          tool_name: pyflakes
